# Generated by Django 3.2.3 on 2021-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlyerPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('pitch', models.CharField(max_length=128)),
                ('flyers_given', models.IntegerField(default=0)),
            ],
        ),
    ]
